"""fileuploaded db add new column name convert db status

Revision ID: 3516f6d980c4
Revises: e8d810852906
Create Date: 2026-10-05 11:18:49.348730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3516f6d980c4'
down_revision: Union[str, Sequence[str], None] = 'e8d810852906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ds_fileuploads', sa.Column('convert_db', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ds_fileuploads', 'convert_db')
    # ### end Alembic commands ###
