"""datascien model creating table issues

Revision ID: e8d810852906
Revises: f76944c6d66c
Create Date: 2026-08-08 20:28:26.926025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d810852906'
down_revision: Union[str, Sequence[str], None] = 'f76944c6d66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ds_fileuploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_status', sa.String(length=50), nullable=False),
    sa.Column('prediction_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ds_fileuploads_file_name'), 'ds_fileuploads', ['file_name'], unique=False)
    op.create_index(op.f('ix_ds_fileuploads_id'), 'ds_fileuploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ds_fileuploads_id'), table_name='ds_fileuploads')
    op.drop_index(op.f('ix_ds_fileuploads_file_name'), table_name='ds_fileuploads')
    op.drop_table('ds_fileuploads')
    # ### end Alembic commands ###
